name: Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    
    - name: crear jar
      run: |
        jar cfm jna.jar MANIFEST.txt ./jnasmartcardio-master/src/*
          
    - name: Crear Test 
      run: |
        java -cp /home/alumno/.m2/repository/junit/junit/4.8.1/junit-4.8.1.jar:./jnasmartcardio-master/src/test/java org.junit.runner.JUnitCore jnasmartcardio.WinscardReaderTestWithCardPresent > log.txt

